-- MySQL Script generated by MySQL Workbench
-- Wed Oct 13 22:30:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema copa_mundo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `copa_mundo` ;

-- -----------------------------------------------------
-- Schema copa_mundo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `copa_mundo` DEFAULT CHARACTER SET utf8 ;
USE `copa_mundo` ;

-- -----------------------------------------------------
-- Table `copa_mundo`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_mundo`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `copa_mundo`.`Grupo` (
  `idGrupo` VARCHAR(1) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_mundo`.`Pais` ;

CREATE TABLE IF NOT EXISTS `copa_mundo`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `selecao` VARCHAR(45) NULL,
  `continente` VARCHAR(45) NULL,
  `tecnico` VARCHAR(45) NULL,
  `pontos` INT NULL,
  `vitorias` INT NULL,
  `empates` INT NULL,
  `derrotas` INT NULL,
  `golspro` INT NULL,
  `golscontra` INT NULL,
  `Grupo_idGrupo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idPais`, `Grupo_idGrupo`),
  INDEX `fk_Pais_Grupo1_idx` (`Grupo_idGrupo` ASC) ,
  CONSTRAINT `fk_Pais_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `copa_mundo`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`Jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_mundo`.`Jogador` ;

CREATE TABLE IF NOT EXISTS `copa_mundo`.`Jogador` (
  `idJogador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `camisa` INT NULL,
  `posicao` VARCHAR(45) NULL,
  `Pais_idPais` INT NOT NULL,
  `situacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idJogador`, `Pais_idPais`),
  INDEX `fk_Jogador_Pais1_idx` (`Pais_idPais` ASC) ,
  CONSTRAINT `fk_Jogador_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `copa_mundo`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`Estadio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_mundo`.`Estadio` ;

CREATE TABLE IF NOT EXISTS `copa_mundo`.`Estadio` (
  `idEstadio` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `localizacao` VARCHAR(45) NULL,
  `capacidade` INT NULL,
  PRIMARY KEY (`idEstadio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`Jogos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_mundo`.`Jogos` ;

CREATE TABLE IF NOT EXISTS `copa_mundo`.`Jogos` (
  `idJogos` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL,
  `Estadio_idEstadio` INT NOT NULL,
  `Pais_idPais_1` INT NOT NULL,
  `Pais_idPais_2` INT NOT NULL,
  `gols_idpais_1` INT NULL,
  `gols_idpais_2` INT NULL,
  `publico` INT NULL,
  PRIMARY KEY (`idJogos`, `Estadio_idEstadio`, `Pais_idPais_1`, `Pais_idPais_2`),
  INDEX `fk_Jogos_Estadio1_idx` (`Estadio_idEstadio` ASC) ,
  INDEX `fk_Jogos_Pais1_idx` (`Pais_idPais_1` ASC) ,
  INDEX `fk_Jogos_Pais2_idx` (`Pais_idPais_2` ASC) ,
  CONSTRAINT `fk_Jogos_Estadio1`
    FOREIGN KEY (`Estadio_idEstadio`)
    REFERENCES `copa_mundo`.`Estadio` (`idEstadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogos_Pais1`
    FOREIGN KEY (`Pais_idPais_1`)
    REFERENCES `copa_mundo`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogos_Pais2`
    FOREIGN KEY (`Pais_idPais_2`)
    REFERENCES `copa_mundo`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`Cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_mundo`.`Cartao` ;

CREATE TABLE IF NOT EXISTS `copa_mundo`.`Cartao` (
  `Jogos_idJogos` INT NOT NULL,
  `Jogador_idJogador` INT NOT NULL,
  `amarelo` TINYINT NULL,
  `vermelho` TINYINT NULL,
  `tempo` VARCHAR(45) NULL,
  PRIMARY KEY (`Jogos_idJogos`, `Jogador_idJogador`),
  INDEX `fk_Cartao_Jogador1_idx` (`Jogador_idJogador` ASC) ,
  CONSTRAINT `fk_Cartao_Jogos1`
    FOREIGN KEY (`Jogos_idJogos`)
    REFERENCES `copa_mundo`.`Jogos` (`idJogos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cartao_Jogador1`
    FOREIGN KEY (`Jogador_idJogador`)
    REFERENCES `copa_mundo`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`Gols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_mundo`.`Gols` ;

CREATE TABLE IF NOT EXISTS `copa_mundo`.`Gols` (
  `Jogos_idJogos` INT NOT NULL,
  `Jogador_idJogador` INT NOT NULL,
  `tempo` VARCHAR(45) NULL,
  PRIMARY KEY (`Jogos_idJogos`, `Jogador_idJogador`),
  INDEX `fk_Gols_Jogos1_idx` (`Jogos_idJogos` ASC) ,
  CONSTRAINT `fk_Gols_Jogador1`
    FOREIGN KEY (`Jogador_idJogador`)
    REFERENCES `copa_mundo`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gols_Jogos1`
    FOREIGN KEY (`Jogos_idJogos`)
    REFERENCES `copa_mundo`.`Jogos` (`idJogos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_mundo`.`Substituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_mundo`.`Substituicao` ;

CREATE TABLE IF NOT EXISTS `copa_mundo`.`Substituicao` (
  `Jogos_idJogos` INT NOT NULL,
  `Jogador_idJogador_sai` INT NOT NULL,
  `Jogador_idJogador_entra` INT NOT NULL,
  `tempo` VARCHAR(45) NULL,
  PRIMARY KEY (`Jogos_idJogos`, `Jogador_idJogador_sai`, `Jogador_idJogador_entra`),
  INDEX `fk_Substituicao_Jogador1_idx` (`Jogador_idJogador_sai` ASC) ,
  INDEX `fk_Substituicao_Jogador2_idx` (`Jogador_idJogador_entra` ASC) ,
  CONSTRAINT `fk_Substituicao_Jogos`
    FOREIGN KEY (`Jogos_idJogos`)
    REFERENCES `copa_mundo`.`Jogos` (`idJogos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substituicao_Jogador1`
    FOREIGN KEY (`Jogador_idJogador_sai`)
    REFERENCES `copa_mundo`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substituicao_Jogador2`
    FOREIGN KEY (`Jogador_idJogador_entra`)
    REFERENCES `copa_mundo`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
